import styles from './ResumeEditor.module.css';

const Field = ({ label, value, onChange, multiline = false, placeholder = '' }) => <label className={styles.field}><span>{label}</span>{multiline ? <textarea value={value || ''} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} rows={4} /> : <input value={value || ''} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} />}</label>;

export default function ResumeEditor({ resume, onChange }) {
  const set = (path, value) => { const copy = structuredClone(resume); const parts = path.split('.'); let node = copy; parts.slice(0, -1).forEach((part) => { node = node[part]; }); node[parts.at(-1)] = value; onChange(copy); };
  const updateItem = (collection, id, changes) => onChange({ ...resume, [collection]: resume[collection].map((item) => item.id === id ? { ...item, ...changes } : item) });
  const remove = (collection, id) => onChange({ ...resume, [collection]: resume[collection].filter((item) => item.id !== id) });
  const move = (collection, index, direction) => { const values = [...resume[collection]]; const target = index + direction; if (target < 0 || target >= values.length) return; const [item] = values.splice(index, 1); values.splice(target, 0, item); onChange({ ...resume, [collection]: values }); };
  const add = (collection) => {
    const templates = {
      experience: { id: crypto.randomUUID(), role: '', company: '', location: '', startDate: '', endDate: '', bullets: [{ id: crypto.randomUUID(), text: '' }] },
      projects: { id: crypto.randomUUID(), name: '', subtitle: '', link: '', startDate: '', endDate: '', bullets: [{ id: crypto.randomUUID(), text: '' }] },
      education: { id: crypto.randomUUID(), institution: '', qualification: '', location: '', startDate: '', endDate: '', details: '' },
    };
    onChange({ ...resume, [collection]: [...resume[collection], templates[collection]] });
  };
  const collectionEditor = (collection, title) => <section className={styles.section}><div className={styles.sectionHead}><h3>{title}</h3><button type="button" className={styles.add} onClick={() => add(collection)}>+ Add</button></div>{resume[collection].map((item, index) => <div className={styles.card} key={item.id}>
    <div className={styles.cardActions}><button type="button" onClick={() => move(collection, index, -1)} disabled={index === 0} aria-label={`Move ${title} item up`}>↑</button><button type="button" onClick={() => move(collection, index, 1)} disabled={index === resume[collection].length - 1} aria-label={`Move ${title} item down`}>↓</button><button type="button" className={styles.delete} onClick={() => remove(collection, item.id)}>Delete</button></div>
    <div className={styles.grid}>{collection === 'experience' && <><Field label="Role" value={item.role} onChange={(value) => updateItem(collection, item.id, { role: value })} /><Field label="Company" value={item.company} onChange={(value) => updateItem(collection, item.id, { company: value })} /><Field label="Location" value={item.location} onChange={(value) => updateItem(collection, item.id, { location: value })} /></>}{collection === 'projects' && <><Field label="Project" value={item.name} onChange={(value) => updateItem(collection, item.id, { name: value })} /><Field label="Subtitle" value={item.subtitle} onChange={(value) => updateItem(collection, item.id, { subtitle: value })} /><Field label="Link" value={item.link} onChange={(value) => updateItem(collection, item.id, { link: value })} /></>}{collection === 'education' && <><Field label="Qualification" value={item.qualification} onChange={(value) => updateItem(collection, item.id, { qualification: value })} /><Field label="Institution" value={item.institution} onChange={(value) => updateItem(collection, item.id, { institution: value })} /><Field label="Details" value={item.details} onChange={(value) => updateItem(collection, item.id, { details: value })} /></>}<Field label="Start" value={item.startDate} onChange={(value) => updateItem(collection, item.id, { startDate: value })} /><Field label="End" value={item.endDate} onChange={(value) => updateItem(collection, item.id, { endDate: value })} /></div>
    {item.bullets && <div className={styles.bullets}><span>Bullet points</span>{item.bullets.map((bullet) => <div className={styles.bullet} key={bullet.id}><textarea rows={2} value={bullet.text} onChange={(e) => updateItem(collection, item.id, { bullets: item.bullets.map((b) => b.id === bullet.id ? { ...b, text: e.target.value } : b) })} /><button type="button" onClick={() => updateItem(collection, item.id, { bullets: item.bullets.filter((b) => b.id !== bullet.id) })}>×</button></div>)}<button type="button" className={styles.textButton} onClick={() => updateItem(collection, item.id, { bullets: [...item.bullets, { id: crypto.randomUUID(), text: '' }] })}>+ Add bullet</button></div>}
  </div>)}</section>;

  return <div className={styles.editor}>
    <section className={styles.section}><h3>Basics</h3><div className={styles.grid}><Field label="Full name" value={resume.name} onChange={(v) => set('name', v)} /><Field label="Professional title" value={resume.title} onChange={(v) => set('title', v)} /><Field label="Email" value={resume.contact.email} onChange={(v) => set('contact.email', v)} /><Field label="Phone" value={resume.contact.phone} onChange={(v) => set('contact.phone', v)} /><Field label="Location" value={resume.contact.location} onChange={(v) => set('contact.location', v)} /></div><Field label="Professional summary" value={resume.summary} onChange={(v) => set('summary', v)} multiline /></section>
    <section className={styles.section}><div className={styles.sectionHead}><h3>Skills</h3><button type="button" className={styles.add} onClick={() => onChange({ ...resume, skillGroups: [...resume.skillGroups, { id: crypto.randomUUID(), name: '', skills: [] }] })}>+ Group</button></div>{resume.skillGroups.map((group) => <div className={styles.skillRow} key={group.id}><input aria-label="Skill group" value={group.name} placeholder="Group" onChange={(e) => updateItem('skillGroups', group.id, { name: e.target.value })} /><input aria-label="Comma-separated skills" value={group.skills.join(', ')} placeholder="Skills, separated by commas" onChange={(e) => updateItem('skillGroups', group.id, { skills: e.target.value.split(',').map((x) => x.trim()).filter(Boolean) })} /><button type="button" onClick={() => remove('skillGroups', group.id)}>×</button></div>)}</section>
    {collectionEditor('experience', 'Experience')}<section className={styles.section}><Field label="Project section heading" value={resume.projectSectionTitle || 'Projects'} onChange={(v) => set('projectSectionTitle', v)} /></section>{collectionEditor('projects', resume.projectSectionTitle || 'Projects')}{collectionEditor('education', 'Education')}
  </div>;
}
