import { useState } from 'react';
import styles from './ResumeEditor.module.css';

const Field = ({ label, value, onChange, multiline = false, placeholder = '' }) => <label className={styles.field}><span>{label}</span>{multiline ? <textarea value={value || ''} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} rows={4} /> : <input value={value || ''} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} />}</label>;

export default function ResumeEditor({ resume, onChange, activeSection = 'all' }) {
  const [skillDrafts, setSkillDrafts] = useState({});
  const set = (path, value) => { const copy = structuredClone(resume); const parts = path.split('.'); let node = copy; parts.slice(0, -1).forEach((part) => { node = node[part]; }); node[parts.at(-1)] = value; onChange(copy); };
  const setLink = (label, url) => { const links = [...(resume.links || [])]; const index = links.findIndex((link) => link.label.toLowerCase() === label.toLowerCase()); if (index >= 0) links[index] = { ...links[index], url }; else links.push({ id: crypto.randomUUID(), label, url }); onChange({ ...resume, links }); };
  const updateItem = (collection, id, changes) => onChange({ ...resume, [collection]: resume[collection].map((item) => item.id === id ? { ...item, ...changes } : item) });
  const remove = (collection, id) => onChange({ ...resume, [collection]: resume[collection].filter((item) => item.id !== id) });
  const move = (collection, index, direction) => { const values = [...resume[collection]]; const target = index + direction; if (target < 0 || target >= values.length) return; const [item] = values.splice(index, 1); values.splice(target, 0, item); onChange({ ...resume, [collection]: values }); };
  const reorder = (collection, sourceId, targetId) => { if (sourceId === targetId) return; const values = [...resume[collection]]; const from = values.findIndex((item) => item.id === sourceId); const to = values.findIndex((item) => item.id === targetId); if (from < 0 || to < 0) return; const [item] = values.splice(from, 1); values.splice(to, 0, item); onChange({ ...resume, [collection]: values }); };
  const dragHandle = (id, label) => <span className={styles.dragHandle} draggable aria-label={`Drag to reorder ${label}`} title="Drag to reorder" onDragStart={(event) => { event.stopPropagation(); event.dataTransfer.effectAllowed = 'move'; event.dataTransfer.setData('text/plain', id); }} onClick={(event) => event.preventDefault()}>⠿</span>;
  const addSkills = (group, value) => { const skills = value.split(',').map((skill) => skill.trim()).filter(Boolean); if (!skills.length) return; updateItem('skillGroups', group.id, { skills: [...group.skills, ...skills] }); setSkillDrafts((drafts) => ({ ...drafts, [group.id]: '' })); };
  const add = (collection) => {
    const templates = {
      experience: { id: crypto.randomUUID(), role: '', company: '', location: '', startDate: '', endDate: '', bullets: [{ id: crypto.randomUUID(), text: '' }] },
      projects: { id: crypto.randomUUID(), name: '', subtitle: '', link: '', startDate: '', endDate: '', bullets: [{ id: crypto.randomUUID(), text: '' }] },
      education: { id: crypto.randomUUID(), institution: '', qualification: '', location: '', startDate: '', endDate: '', details: '' },
    };
    onChange({ ...resume, [collection]: [...resume[collection], templates[collection]] });
  };
  const collectionEditor = (collection, title) => <section className={styles.section}><div className={styles.sectionHead}><h3>{title}</h3><button type="button" className={styles.add} onClick={() => add(collection)}>+ Add</button></div>{resume[collection].map((item) => <details className={styles.card} key={item.id} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); reorder(collection, event.dataTransfer.getData('text/plain'), item.id); }}>
    <summary className={styles.accordionSummary}>{dragHandle(item.id, title)}<span className={styles.accordionTitle}>{collection === 'experience' ? item.role || 'New role' : collection === 'projects' ? item.name || 'New project' : item.qualification || 'Education'}</span><span className={styles.accordionMeta}>{collection === 'experience' ? item.company : collection === 'projects' ? item.subtitle : item.institution}</span><span className={styles.accordionCount}>{collection === 'experience' ? `${item.bullets.length} points` : ''}</span><span className={styles.summaryDelete} role="button" tabIndex={0} onClick={(event) => { event.preventDefault(); event.stopPropagation(); remove(collection, item.id); }} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); remove(collection, item.id); } }}>×</span></summary>
    <div className={styles.cardBody}>
    <div className={styles.grid}>{collection === 'experience' && <><Field label="Role" value={item.role} onChange={(value) => updateItem(collection, item.id, { role: value })} /><Field label="Company" value={item.company} onChange={(value) => updateItem(collection, item.id, { company: value })} /><Field label="Location" value={item.location} onChange={(value) => updateItem(collection, item.id, { location: value })} /></>}{collection === 'projects' && <><Field label="Project" value={item.name} onChange={(value) => updateItem(collection, item.id, { name: value })} /><Field label="Subtitle" value={item.subtitle} onChange={(value) => updateItem(collection, item.id, { subtitle: value })} /><Field label="Link" value={item.link} onChange={(value) => updateItem(collection, item.id, { link: value })} /></>}{collection === 'education' && <><Field label="Qualification" value={item.qualification} onChange={(value) => updateItem(collection, item.id, { qualification: value })} /><Field label="Institution" value={item.institution} onChange={(value) => updateItem(collection, item.id, { institution: value })} /><Field label="Details" value={item.details} onChange={(value) => updateItem(collection, item.id, { details: value })} /></>}<Field label="Start" value={item.startDate} onChange={(value) => updateItem(collection, item.id, { startDate: value })} /><Field label="End" value={item.endDate} onChange={(value) => updateItem(collection, item.id, { endDate: value })} /></div>
    {item.bullets && <div className={styles.bullets}><span>Bullet points</span>{item.bullets.map((bullet) => <div className={styles.bullet} key={bullet.id}><textarea rows={2} value={bullet.text} onChange={(e) => updateItem(collection, item.id, { bullets: item.bullets.map((b) => b.id === bullet.id ? { ...b, text: e.target.value } : b) })} /><button type="button" onClick={() => updateItem(collection, item.id, { bullets: item.bullets.filter((b) => b.id !== bullet.id) })}>×</button></div>)}<button type="button" className={styles.textButton} onClick={() => updateItem(collection, item.id, { bullets: [...item.bullets, { id: crypto.randomUUID(), text: '' }] })}>+ Add bullet</button></div>}
    </div>
  </details>)}</section>;

  return <div className={styles.editor}>
    {(activeSection === 'all' || activeSection === 'personal') && <section className={styles.section}><h3>Personal information</h3><div className={styles.grid}><Field label="Full name" value={resume.name} onChange={(v) => set('name', v)} /><Field label="Professional title" value={resume.title} onChange={(v) => set('title', v)} /><Field label="Email" value={resume.contact.email} onChange={(v) => set('contact.email', v)} /><Field label="Phone" value={resume.contact.phone} onChange={(v) => set('contact.phone', v)} /><Field label="Location" value={resume.contact.location} onChange={(v) => set('contact.location', v)} /><Field label="LinkedIn" value={resume.links?.find((link) => /linkedin/i.test(link.label))?.url} onChange={(v) => setLink('LinkedIn', v)} /><Field label="Website" value={resume.links?.find((link) => /website|portfolio|personal/i.test(link.label))?.url} onChange={(v) => setLink('Website', v)} /></div><Field label="Career summary" value={resume.summary} onChange={(v) => set('summary', v)} multiline /></section>}
    {(activeSection === 'all' || activeSection === 'skills') && <section className={styles.section}><div className={styles.sectionHead}><h3>Skill groups</h3><button type="button" className={styles.add} onClick={() => onChange({ ...resume, skillGroups: [...resume.skillGroups, { id: crypto.randomUUID(), name: '', skills: [] }] })}>+ Group</button></div>{resume.skillGroups.map((group, index) => <details className={styles.card} key={group.id} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); reorder('skillGroups', event.dataTransfer.getData('text/plain'), group.id); }}><summary className={styles.accordionSummary}>{dragHandle(group.id, 'skill group')}<span className={styles.accordionTitle}>{group.name || 'New skill group'}</span><span className={styles.accordionCount}>{group.skills.length} skills</span><span className={styles.summaryDelete} role="button" tabIndex={0} onClick={(event) => { event.preventDefault(); event.stopPropagation(); remove('skillGroups', group.id); }} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); remove('skillGroups', group.id); } }}>×</span></summary><div className={styles.cardBody}><label className={styles.field}><span>Title</span><input value={group.name} placeholder="Skill group title" onChange={(e) => updateItem('skillGroups', group.id, { name: e.target.value })} /></label><label className={styles.field}><span>Skills</span><div className={styles.skillInputRow}><input value={skillDrafts[group.id] || ''} placeholder="Add skills separated by commas" onChange={(e) => setSkillDrafts((drafts) => ({ ...drafts, [group.id]: e.target.value }))} onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ',') { e.preventDefault(); addSkills(group, skillDrafts[group.id] || ''); } }} /><button type="button" onClick={() => addSkills(group, skillDrafts[group.id] || '')}>+ Add</button></div><small>Press Enter or use commas to add multiple skills.</small></label><div className={styles.skillChips}>{group.skills.map((skill, skillIndex) => <span className={styles.skillChip} key={`${skill}-${skillIndex}`}>{skill}<button type="button" aria-label={`Remove ${skill}`} onClick={() => updateItem('skillGroups', group.id, { skills: group.skills.filter((_, i) => i !== skillIndex) })}>×</button></span>)}</div><div className={styles.cardActions}><button type="button" onClick={() => move('skillGroups', index, -1)} disabled={index === 0} aria-label="Move skill group up">↑</button><button type="button" onClick={() => move('skillGroups', index, 1)} disabled={index === resume.skillGroups.length - 1} aria-label="Move skill group down">↓</button></div></div></details>)}</section>}
    {(activeSection === 'all' || activeSection === 'experience') && collectionEditor('experience', 'Experience')}
    {(activeSection === 'all' || activeSection === 'projects') && <><section className={styles.section}><Field label="Project section heading" value={resume.projectSectionTitle || 'Projects'} onChange={(v) => set('projectSectionTitle', v)} /></section>{collectionEditor('projects', resume.projectSectionTitle || 'Projects')}</>}
    {(activeSection === 'all' || activeSection === 'education') && collectionEditor('education', 'Education')}
    {(activeSection === 'all' || activeSection === 'more') && <section className={styles.section}><div className={styles.sectionHead}><h3>Certifications & more</h3><button type="button" className={styles.add} onClick={() => onChange({ ...resume, certifications: [...(resume.certifications || []), { id: crypto.randomUUID(), name: '', issuer: '', date: '' }] })}>+ Add</button></div>{(resume.certifications || []).map((item) => <div className={styles.skillRow} key={item.id}><input aria-label="Certification name" value={item.name} placeholder="Certification" onChange={(e) => updateItem('certifications', item.id, { name: e.target.value })} /><input aria-label="Issuer and date" value={[item.issuer, item.date].filter(Boolean).join(' · ')} placeholder="Issuer · date" onChange={(e) => { const [issuer = '', date = ''] = e.target.value.split('·').map((part) => part.trim()); updateItem('certifications', item.id, { issuer, date }); }} /><button type="button" onClick={() => remove('certifications', item.id)}>×</button></div>)}{!resume.certifications?.length && <p className={styles.emptyHint}>No certifications yet. Add any relevant credentials.</p>}</section>}
  </div>;
}
